#
# Created on Sat Mar 20 2021
#
# Copyright (c) 2021 Hienlh
# Checkout more resource here: https://github.com/hienlh
#

name: Dart

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: pub-cache
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          path: ~/.pub-cache

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          branch: stable
      - name: Run test
        run: |
          flutter doctor
          flutter test
